export const GEOHASH        = 'GEOHASH'
export const ADD_CART       = 'ADD_CART'
export const REMOVE_CART    = 'REMOVE_CART'
export const SHOPID         = 'SHOPID'
export const CLEAR_CART     = 'CLEAR_CART'
export const INIT_CART      = 'INIT_CART'
